# Generated by Django 3.0.4 on 2020-03-16 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0003_auto_20200316_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Date_Added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Filephile.User'),
        ),
    ]
