# Generated by Django 3.0.4 on 2020-03-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0008_auto_20200318_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='Filephile.Group'),
        ),
    ]
