# Generated by Django 3.0.4 on 2020-03-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0009_auto_20200318_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='groups',
        ),
    ]
