# Generated by Django 3.0.4 on 2020-03-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0010_auto_20200318_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='Filephile.User'),
        ),
    ]
