# Generated by Django 3.0.4 on 2020-03-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0011_auto_20200318_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, to='Filephile.User'),
        ),
    ]
