# Generated by Django 3.0.4 on 2020-03-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0012_auto_20200318_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='Filephile.User'),
        ),
    ]
