# Generated by Django 3.0.4 on 2020-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0015_auto_20200318_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='groups',
            field=models.ManyToManyField(blank=True, to='Filephile.Group'),
        ),
    ]
