# Generated by Django 3.0.4 on 2020-03-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0016_file_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Filephile.Group')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Filephile.User')),
            ],
        ),
    ]
