# Generated by Django 3.0.4 on 2020-03-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0017_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filephile.User'),
        ),
    ]
