# Generated by Django 3.0.4 on 2020-03-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filephile', '0020_auto_20200318_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager',
            new_name='name',
        ),
    ]
